### ISSUE TITLE
windows default setting doesn't allow for rebasing

### ISSUE THREAD

**Issue by Naokimi** [lewagon/dotfiles#104]
Setup environment on Windows using the guide.
When trying to `git rebase -i`, git doesn't wait on VSCode to close and just continues the rebasing process leading to getting stuck in `|REBASE` "branch" from which I can quit only by running `rm -fr ".git/rebase-merge"` (and resetting the rebasing with it...)

Proposal:
change line https://github.com/lewagon/dotfiles/blob/master/gitconfig#L14 from `editor = code` to `editor = code --wait`

**Comment by dmilon** [comment]
Hi @Naokimi :wave: Thank you for your feedback. 

I've added the `--wait` flag so that VS Code will wait for the window to be closed before returning :ok_hand: 

Just so you know, you can always abort a pending rebase with the command `git rebase --abort`
