### ISSUE TITLE
pyenv lacking in .zshrc plugins 

### ISSUE THREAD

**Issue by vitorsouton** [lewagon/dotfiles#146]
During the setup day for batch #1365, many students had the issue of pyenv command not working after cloning dotfiles. After checking the .zshrc file, the pyenv plugin is missing from the plugins (line 7). After adding it to the plugins and restarting the terminal, the pyenv command was working properly.

**Comment by ssaunier** [comment]
Hmm I don't get it, it's not commented in the repo:

https://github.com/lewagon/dotfiles/blob/adf05d5bffffc08ad040fb9c491ebea0350a5ba2/zshrc#L26

Do you have more details?

**Comment by vitorsouton** [comment]
I'm not sure what happened, for some restarting the terminal was enough, for others the problem was solved only after adding the plugin to the plugins.

**Comment by ssaunier** [comment]
OK, thanks for reporting, we'll monitor this one in the next Setup day and see if we make a reproductible case 🙏
