### ISSUE TITLE
As for gitignore and gitconfig files

### ISSUE THREAD

**Issue by hidehiro98** [lewagon/dotfiles#30]
What are `gitignore` and `gitconfig` for?
Are these files not used anymore?

**Comment by hidehiro98** [comment]
I got these files are linked with symbolic links in home directory by `install.sh`.
But where is the command like `git config --global core.excludesfile ~/.gitignore`?
https://stackoverflow.com/questions/5270917/why-doesnt-my-global-gitignore-file-ignore

**Comment by hidehiro98** [comment]
I checked the git config with `git config --list | grep core`.
```
core.pager=less -FRSX
core.editor='/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl' -n -w
core.autocrlf=input
```

It looks `gitignore` file is not used as a global config for git.

**Comment by ssaunier** [comment]
You're right, I'll remove the `gitignore` file.
