### ISSUE TITLE
File explorer alias for WSL

### ISSUE THREAD

**Issue by ElvisDot** [lewagon/dotfiles#65]
Something like this in aliases would be nice
```
alias start='cmd.exe /c start'
```

**Comment by dmilon** [comment]
From the Linux filesystem terminal, you can always open the Windows file explorer anywhere [with `explorer.exe .`](https://github.com/lewagon/data-setup/blob/master/WINDOWS.md#open-the-windows-file-explorer-from-the-ubuntu-terminal)
